
server:
  port: 9177

spring:
  security:
    oauth2:
      client:
        provider:
          myProvider:
            authorizationUri: http://localhost:9178/oauth/authorize
            tokenUri: http://localhost:9178/oauth/token
            #userInfoUri:
            #userInfoAuthenticationMethod:
            #userNameAttribute:
            #jwkSetUri:
            #issuerUri:
        registration:
          myRegistration
            provider: myProvider
            clientId: my-clientId
            clientSecret: 123456
            #clientAuthenticationMethod:
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:9177/login/oauth2/code/authorizationServer
            scope: query
            #clientName: