
server:
  port: 9177

spring:
  security:
    oauth2:
      client:
        provider:
          authorizationserver:
            authorizationUri: http://localhost:9178/oauth/authorize
            tokenUri: http://localhost:9178/oauth/token
            userInfoUri: http://localhost:9178/me
            #userInfoAuthenticationMethod:
            userNameAttribute: "name"
            #jwkSetUri:
            #issuerUri:
        registration:
          authorizationserver:
            provider: authorizationserver
            clientId: my-clientId
            clientSecret: 123456
            clientAuthenticationMethod: basic
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:9177/login/oauth2/code/authorizationserver
            scope: profile,email,phone
            #clientName: